Домашка спринт 14
IsaevMilan/Playlist_Maker pull request #8
Opened 2023-07-12 13:50 UTC by IsaevMilan

2023-07-13 12:02 UTC, NoDopezzz requested changes

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaAdapter.kt
> +        private const val CLICK_DEBOUNCE_DELAY = 1000L
⏫ В названии константных переменных, лучше указывать название величины. В данном случае `CLICK_DEBOUNCE_DELAY_MS`

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaAdapter.kt
> +    private val searchActivityObj = SearchActivity()
⏫ В данном случае нам будет правильнее обращаться не к `Activity`, а напрямую к `SearchHistory`. Иначе мы в нашем адаптере создаем Activity - достаточно тяжелый объект - но в дальнейшем его никак не используем (например для открытия)

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaAdapter.kt
> +    private val searchActivityObj = SearchActivity()
Вообще лучше стараться всегда себя останавливать, когда есть желание вручную создать `Activity`, ведь этим должна заниматься система

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaPlayerActivity.kt
> +    private var mainThreadHandler: Handler? = null
⏫`Handler` не привязан к жизненному циклу `Activity`, поэтому мы можем его смело создать до `onCreate` при инициализации `MediaPlayerActivity`

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaPlayerActivity.kt
> +    var time = 0
⏫ Поле `time` используется только в классе `MediaPlayerActivity`, поэтому мы можем сделать `private`

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaPlayerActivity.kt
> +            getImage.replace("100x100bb.jpg", "512x512bb.jpg")
⏫ `replace("100x100bb.jpg", "512x512bb.jpg")` уже произошел на 64 строчке

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaPlayerActivity.kt
> +            playButton.visibility = View.VISIBLE
⏫ Вместо использования двух `View` кнопок, мы можем использовать лишь одну и менять их `drawable`. С точки зрения производительности такой подход будет чуть более оптимальный, т.к. мы будет вызывать перерисовку лишь одного элемента вместо двух

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaPlayerActivity.kt
> +    fun timing(): Runnable {
⚠️ Метод `timing()` на каждый вызов возвращает новый объект `Runnable`. Таким образом при каждом новом вызове startPlayer количество колбеков в handler'е будет увеличиваться, что негативно будет сказываться на производительности. 
`Runnable` стоит вынести в поле и передавать его mainThreadHandler при вызове `startPlayer()`. Также стоит не забывать очищать Handler при паузе плеера - чтобы мы лишний раз цикл не гоняли, и при смерти экрана - чтобы не столкнуться с проблемами обновления `View`, когда экрана уже нет и утечками памяти.

2023-07-13 12:02 UTC, kirillNay commented on app/src/main/java/com/example/myplaylistmaker/MediaPlayerActivity.kt
> +        super.onPause()
⚠️ Кажется, что вызов метода жизненного цикла `Activity` тут лишний

2023-07-13 12:02 UTC, NoDopezzz commented on app/src/main/java/com/example/myplaylistmaker/SearchActivity.kt
> +        val searchRunnable = Runnable { requestToServer() }
⏫ Советую тебе немного изменить структуру твоих методов и вынести их из `onCreate`. Вложенные методы редко являются полезными и зачастую они мешают восприятию кода

2023-07-13 12:02 UTC, NoDopezzz commented on app/src/main/res/drawable/pause_button.xml
> +      android:fillColor="#1A1B22"/>
⏫ Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в `drawable` и `drawable-night`, мы можем создать одну иконку в `drawable`, а файл ресурса с цветом будет задан в `values` и `values-night`.

2023-08-04 08:08 UTC, NoDopezzz approved these changes

2023-09-09 14:09 UTC, Charmandik commented on .idea/gradle.xml
Добавь этот тип файлов в гитигнор, их не нужно отслеживать в гите

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/app/App.kt
> +        var trackHistoryList = ArrayList<Track>()
Данная переменная не используется, стоит ее удалить

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/data/dto/PlayerRepositoryImpl.kt
> +        Log.d("PlayerRepositoryImpl", mediaPlayer.isPlaying.toString())
Не рекомендую оставлять логи в коде, так код будет выглядеть чище

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/data/network/RetrofitNetworkClient.kt
> +                return Response().apply { resultCode = 400 }
Числа, которые просто так вливаются в код, зачастую очень сложно понять и их называют магическими числами. Используй константы, для того, чтобы дать имена своим числам Рекомендую к прочтению статью на эту тему : https://bureau.ru/soviet/20230406/

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/domain/models/Track.kt
> +    val trackName: String, // Название композиции
Старайся не оставлять комментарии, как правило, они долго не удаляются и визуально загрязняют код

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/presentation/ui/activities/MediaPlayerActivity.kt
> +        playerTrackName.text = track?.trackName ?: "Unknown Track"
Рекомендуется выносить строки в константы, используя companion object.
Пример правильной реализации:
class MyClass {
    companion object {
        private const val STRING_NAME = "Твоё значение"
    }
}

Такой подход позволит избежать повторения строковых значений в коде и обеспечит более чистую и легко поддерживаемую структуру.

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/presentation/ui/activities/SearchActivity.kt
> +                searchHistory.isGone = true
Для управления видимостью можно использовать свойство isVisible, устанавив значение false

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/presentation/ui/activities/SearchActivity.kt
> +            mediaRecycler.visibility = GONE
Я бы рекомендовал пользоваться одним подходом в проекте для управления видимостью, так код будет легче читаться и выглядеть чище

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/presentation/ui/adapters/MediaAdapter.kt
> +    private class TrackItemCallback : DiffUtil.ItemCallback<Track>() {
Старайся разносить разные классы или интерфейсы по разным файлам. Один класс/интерфейс в один файл.

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/res/layout/track_item.xml
> +        tools:text="Smells Like Teen Spirit Long loooooong teeeeeext " />
Чтобы самому было проще понимать, где в верстке текст, который отображается только в превью студии, а где текст, который "зашит", рекомендую текста, используемые в атрибуте tools, оборачивать в квадратные скобки.

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/res/layout/track_item.xml
> +            android:id="@+id/dot"
Для более простого использования различных классов view рекомендую использовать следующий трюк: К имени переменной добавлять префикс в виде "аббревиатуры" класса, к которой она относится, для TextView - tv, ImageView - iv, RecyclerView - rv и т.д.. Например, у тебя есть RecyclerView для треков, в этом случае будет rvTracks

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/presentation/ui/adapters/MediaAdapter.kt
> +        private const val CLICK_THROTTLE_DELAY = 1000L
При именовании констант для промежутка времени рекомендую всегда в конце добавлять единицу времени, например _MILLIS, _IN_SECONDS, _HOURS и т.д.

2023-09-09 14:09 UTC, Charmandik commented on app/src/main/java/com/example/myplaylistmaker/app/App.kt
> +        lateinit var savedHistory: SharedPreferences
Вместо использования lateinit, я рекомендую тебе использовать подход с добавлением nullability к типу объекта с оператором ?. и сразу проинициализировать его значением null. Это решение позволяет избежать ошибок, связанных с попытками доступа к неинициализированным объектам, которые могут привести к непредсказуемому поведению или крашам приложения. Хотя это может добавить некоторую дополнительную работу при обращении к объекту через оператор ?. , но это значительно повысит безопасность приложения, так как ты будешь уверен, что объект всегда либо имеет значение, либо равен null, и не будет вызывать исключительных ситуаций.Можешь еще прочитать статью на эту тему https://habr.com/ru/companies/maxilect/articles/590061

2023-09-12 06:22 UTC, IsaevMilan commented on app/src/main/java/com/example/myplaylistmaker/data/dto/PlayerRepositoryImpl.kt
> +        Log.d("PlayerRepositoryImpl", mediaPlayer.isPlaying.toString())
Ok

2023-09-12 06:22 UTC, IsaevMilan commented on app/src/main/java/com/example/myplaylistmaker/data/network/RetrofitNetworkClient.kt
> +                return Response().apply { resultCode = 400 }
Понял)

2023-09-12 06:22 UTC, IsaevMilan commented on app/src/main/java/com/example/myplaylistmaker/domain/models/Track.kt
> +    val trackName: String, // Название композиции
Ок

2023-09-12 20:49 UTC, merged